development:
  adapter: postgresql
  encoding: unicode
  database: courier_service_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: courier_service_test
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: courier_service_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: 5